# -*- coding: utf-8 -*- This line is just for your information, the python plugin will not use the first line
insert into about_db values('layer_styles', '*', '', '', 'QGIS specific table for storing layer styles in the database')
CREATE TABLE layer_styles(id INTEGER PRIMARY KEY AUTOINCREMENT,f_table_catalog varchar(256),f_table_schema varchar(256),f_table_name varchar(256),f_geometry_column varchar(256),styleName varchar(30),styleQML text,styleSLD text,useAsDefault boolean,description text,owner varchar(30),ui text,update_time timestamp DEFAULT CURRENT_TIMESTAMP)
insert into layer_styles("f_table_catalog", "f_table_schema", "f_table_name", "f_geometry_column", "styleName", "useAsDefault", "description", "update_time") values('CHANGETODBPATH', '', 'obs_points','Geometry','obs_points','1','CHANGETOCURRENTDATETIME','CHANGETOCURRENTDATETIME');
insert into layer_styles("f_table_catalog", "f_table_schema", "f_table_name", "f_geometry_column", "styleName", "useAsDefault", "description", "update_time") values('CHANGETODBPATH', '', 'obs_lines','Geometry','obs_lines','1','CHANGETOCURRENTDATETIME','CHANGETOCURRENTDATETIME');
insert into layer_styles("f_table_catalog", "f_table_schema", "f_table_name", "f_geometry_column", "styleName", "useAsDefault", "description", "update_time") values('CHANGETODBPATH', '', 'obs_p_w_strat','Geometry','obs_p_w_strat','1','CHANGETOCURRENTDATETIME','CHANGETOCURRENTDATETIME');
insert into layer_styles("f_table_catalog", "f_table_schema", "f_table_name", "f_geometry_column", "styleName", "useAsDefault", "description", "update_time") values('CHANGETODBPATH', '', 'obs_p_w_lvl','Geometry','obs_p_w_lvl','1','CHANGETOCURRENTDATETIME','CHANGETOCURRENTDATETIME');
insert into layer_styles("f_table_catalog", "f_table_schema", "f_table_name", "f_geometry_column", "styleName", "useAsDefault", "description", "update_time") values('CHANGETODBPATH', '', 'obs_p_w_qual_lab','Geometry','obs_p_w_qual_lab','1','CHANGETOCURRENTDATETIME','CHANGETOCURRENTDATETIME');
insert into layer_styles("f_table_catalog", "f_table_schema", "f_table_name", "f_geometry_column", "styleName", "useAsDefault", "description", "update_time") values('CHANGETODBPATH', '', 'obs_p_w_qual_field','Geometry','obs_p_w_qual_field','1','CHANGETOCURRENTDATETIME','CHANGETOCURRENTDATETIME');
insert into layer_styles("f_table_catalog", "f_table_schema", "f_table_name", "f_geometry_column", "styleName", "useAsDefault", "description", "update_time") values('CHANGETODBPATH', '', 'w_lvls_last_geom','Geometry','w_lvls_last_geom','1','CHANGETOCURRENTDATETIME','CHANGETOCURRENTDATETIME');
insert into layer_styles("f_table_catalog", "f_table_schema", "f_table_name", "f_geometry_column", "styleName", "useAsDefault", "description", "update_time") values('CHANGETODBPATH', '', 'w_qual_field','Geometry','w_qual_field','1','CHANGETOCURRENTDATETIME','CHANGETOCURRENTDATETIME');
insert into layer_styles("f_table_catalog", "f_table_schema", "f_table_name", "f_geometry_column", "styleName", "useAsDefault", "description", "update_time") values('CHANGETODBPATH', '', 'w_qual_lab','Geometry','w_qual_lab','1','CHANGETOCURRENTDATETIME','CHANGETOCURRENTDATETIME');
insert into layer_styles("f_table_catalog", "f_table_schema", "f_table_name", "f_geometry_column", "styleName", "useAsDefault", "description", "update_time") values('CHANGETODBPATH', '', 'w_flow','Geometry','w_flow','1','CHANGETOCURRENTDATETIME','CHANGETOCURRENTDATETIME');
insert into layer_styles("f_table_catalog", "f_table_schema", "f_table_name", "f_geometry_column", "styleName", "useAsDefault", "description", "update_time") values('CHANGETODBPATH', '', 'w_levels','Geometry','w_levels','1','CHANGETOCURRENTDATETIME','CHANGETOCURRENTDATETIME');
insert into layer_styles("f_table_catalog", "f_table_schema", "f_table_name", "f_geometry_column", "styleName", "useAsDefault", "description", "update_time") values('CHANGETODBPATH', '', 'stratigraphy','Geometry','stratigraphy','1','CHANGETOCURRENTDATETIME','CHANGETOCURRENTDATETIME');
