# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'secplotdialog_ui.ui'
#
# Created: Mon Jan 27 22:10:07 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_SecPlotWindow(object):
    def setupUi(self, SecPlotWindow):
        SecPlotWindow.setObjectName(_fromUtf8("SecPlotWindow"))
        SecPlotWindow.setWindowModality(QtCore.Qt.NonModal)
        SecPlotWindow.resize(698, 445)
        self.gridLayout_3 = QtGui.QGridLayout(SecPlotWindow)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.frame = QtGui.QFrame(SecPlotWindow)
        self.frame.setMinimumSize(QtCore.QSize(110, 350))
        self.frame.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label = QtGui.QLabel(self.frame)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.wlvltableComboBox = QtGui.QComboBox(self.frame)
        self.wlvltableComboBox.setObjectName(_fromUtf8("wlvltableComboBox"))
        self.verticalLayout_2.addWidget(self.wlvltableComboBox)
        self.verticalLayout_6.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.label_3)
        self.datetimetextEdit = QtGui.QTextEdit(self.frame)
        self.datetimetextEdit.setObjectName(_fromUtf8("datetimetextEdit"))
        self.verticalLayout.addWidget(self.datetimetextEdit)
        self.verticalLayout_6.addLayout(self.verticalLayout)
        self.line = QtGui.QFrame(self.frame)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_6.addWidget(self.line)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_3.addWidget(self.label_4)
        self.colorComboBox = QtGui.QComboBox(self.frame)
        self.colorComboBox.setObjectName(_fromUtf8("colorComboBox"))
        self.verticalLayout_3.addWidget(self.colorComboBox)
        self.verticalLayout_6.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_4.addWidget(self.label_5)
        self.textcolComboBox = QtGui.QComboBox(self.frame)
        self.textcolComboBox.setObjectName(_fromUtf8("textcolComboBox"))
        self.verticalLayout_4.addWidget(self.textcolComboBox)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_6 = QtGui.QLabel(self.frame)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_6)
        self.barwidthdoubleSpinBox = QtGui.QDoubleSpinBox(self.frame)
        self.barwidthdoubleSpinBox.setDecimals(1)
        self.barwidthdoubleSpinBox.setProperty("value", 2.0)
        self.barwidthdoubleSpinBox.setObjectName(_fromUtf8("barwidthdoubleSpinBox"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.barwidthdoubleSpinBox)
        self.verticalLayout_6.addLayout(self.formLayout)
        self.line_2 = QtGui.QFrame(self.frame)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_6.addWidget(self.line_2)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_5.addWidget(self.label_2)
        self.drillstoplineEdit = QtGui.QLineEdit(self.frame)
        self.drillstoplineEdit.setObjectName(_fromUtf8("drillstoplineEdit"))
        self.verticalLayout_5.addWidget(self.drillstoplineEdit)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.pushButton = QtGui.QPushButton(self.frame)
        self.pushButton.setMaximumSize(QtCore.QSize(250, 16777215))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.verticalLayout_6.addWidget(self.pushButton)
        self.gridLayout_2.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame)
        self.plotareawidget = QtGui.QWidget(SecPlotWindow)
        self.plotareawidget.setMinimumSize(QtCore.QSize(500, 0))
        self.plotareawidget.setObjectName(_fromUtf8("plotareawidget"))
        self.gridLayout = QtGui.QGridLayout(self.plotareawidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.mplplotlayout = QtGui.QVBoxLayout()
        self.mplplotlayout.setObjectName(_fromUtf8("mplplotlayout"))
        self.gridLayout.addLayout(self.mplplotlayout, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.plotareawidget)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.label.setBuddy(self.wlvltableComboBox)
        self.label_3.setBuddy(self.wlvltableComboBox)
        self.label_4.setBuddy(self.wlvltableComboBox)
        self.label_5.setBuddy(self.wlvltableComboBox)
        self.label_6.setBuddy(self.wlvltableComboBox)
        self.label_2.setBuddy(self.wlvltableComboBox)

        self.retranslateUi(SecPlotWindow)
        QtCore.QMetaObject.connectSlotsByName(SecPlotWindow)

    def retranslateUi(self, SecPlotWindow):
        SecPlotWindow.setWindowTitle(QtGui.QApplication.translate("SecPlotWindow", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("SecPlotWindow", "table for w level:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("SecPlotWindow", "date time", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("SecPlotWindow", "color:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("SecPlotWindow", "text:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("SecPlotWindow", "width(%)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("SecPlotWindow", "drillstop:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("SecPlotWindow", "Replot", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    SecPlotWindow = QtGui.QDialog()
    ui = Ui_SecPlotWindow()
    ui.setupUi(SecPlotWindow)
    SecPlotWindow.show()
    sys.exit(app.exec_())

